AllCops:
  # Make version explicit for Hound
  TargetRubyVersion: 2.4.2
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - db/migrate/*

Metrics/AbcSize:
  Enabled: true
  Exclude:
    - db/migrate/*
