AllCops:
  # Make version explicit for Hound
  TargetRubyVersion: 2.4.2
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "*.inky-slim"
    - "**/*.erb"

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - config/routes.rb
    - config/environments/*

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - db/migrate/*

Metrics/AbcSize:
  Enabled: true
  Exclude:
    - db/migrate/*

Style/Documentation:
  Enabled: true
  Exclude:
    - db/migrate/*

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - db/migrate/*
