linters:
  ElsePlacement:
    enabled: true
    style: new_line
  SelectorDepth:
    enabled: true
    max_depth: 3
  StringQuotes:
    enabled: true
    style: single_quotes
  ElsePlacement:
    enabled: true
    style: new_line
  LeadingZero:
    enabled: true
    style: exclude_zero
  PropertyCount:
    enabled: trues
    include_nested: false
    max_properties: 10
  Shorthand:
    enabled: true
    allowed_shorthands: [1, 2, 3, 4]
