linters:
  ElsePlacement:
    enabled: true
    style: new_line
  SelectorDepth:
    enabled: true
    max_depth: 3
  StringQuotes:
    enabled: true
    style: single_quotes
  ElsePlacement:
    enabled: true
    style: new_line
  LeadingZero:
    enabled: true
    style: exclude_zero
