# Allow users to register new accounts
enable_account_registration: false
# The location for storing Paperclip attachments, such as profile pictures
attachment_storage: 'public/system'
# The location for storing files, such as Git repositories
file_storage: 'system'
