# The location for storing Paperclip attachments, such as profile pictures
attachment_storage: 'public/spec/system'
# The location for storing files, such as Git repositories
file_storage: 'spec/tmp'
# The location for storing lock files
lock_storage: 'spec/tmp/locks'
# Google Drive Test Folder:
# https://drive.google.com/drive/u/0/folders/1_T9Pw8YGc0y5iWOSX-90SzQ1CTUGFmKR
google_drive_test_folder: 'https://drive.google.com/drive/u/0/folders/1_T9Pw8YGc0y5iWOSX-90SzQ1CTUGFmKR'
google_drive_test_folder_id: '1_T9Pw8YGc0y5iWOSX-90SzQ1CTUGFmKR'
