# The location for storing Paperclip attachments, such as profile pictures
attachment_storage: 'public/spec/system'
# The location for storing files, such as Git repositories
file_storage: 'spec/tmp'
# The location for storing lock files
lock_storage: 'spec/tmp/locks'
