# The location for storing files, such as Git repositories
file_storage: 'spec/tmp'
# Google Drive Test Folder:
# https://drive.google.com/drive/u/0/folders/1_T9Pw8YGc0y5iWOSX-90SzQ1CTUGFmKR
google_drive_test_folder: '1_T9Pw8YGc0y5iWOSX-90SzQ1CTUGFmKR'
